# Generated by Django 6.0.2 on 2026-03-28 15:09

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gif_uuid_to_nanoid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gif',
            options={'ordering': ['-copy_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='gif',
            name='copy_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gif',
            name='id',
            field=models.CharField(default=gallery.models.generate_nanoid, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
