# Generated by Django 6.0.2 on 2026-05-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnails/'),
        ),
    ]
