# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v4
      with:
        node-version: '24' 
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build
      run: ./build.sh -c release --arch x86_64 --arch arm64
      working-directory: ./clients/macos/
    - name: Package release
      uses: urban233/create-dmg-actions@v0.0.2
      with:
        dmg_name: 'GIFGallery Client'
        src_dir: './clients/macos/build/GIF Gallery.app'
    - name: 'Upload macOS Build Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: GIFGallery
        path: builds/ProjectAnalyzer-macos
      
